services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=subclub_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=subclub'
    ports:
      - '5432:5432'
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U subclub -d subclub_db'"]

  app:
    image: 'app'
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy

#  front:
#    build:
#      context: 'front'
#      dockerfile: 'web/Dockerfile'
#    ports:
#      - '80:3000'
#    depends_on:
#      app:
#        condition: service_started